package com.rcai.pm.document;
import com.rcai.pm.audit.AuditService; import com.rcai.pm.common.ApiException; import com.rcai.pm.project.*; import com.rcai.pm.user.*;
import org.springframework.core.io.Resource; import org.springframework.http.*; import org.springframework.security.core.Authentication; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.multipart.MultipartFile;
import java.time.Instant; import java.util.*;
@Service @Transactional(readOnly=true)
public class DocumentService{
 private final DocumentRepository docs; private final DocumentVersionRepository versions; private final ProjectRepository projects; private final ProjectMemberRepository members; private final UserAccountRepository users; private final FileStorage storage; private final AuditService audit;
 public DocumentService(DocumentRepository d,DocumentVersionRepository v,ProjectRepository p,ProjectMemberRepository m,UserAccountRepository u,FileStorage s,AuditService a){docs=d;versions=v;projects=p;members=m;users=u;storage=s;audit=a;}
 public List<DocumentView> list(Long projectId,Authentication auth){UserAccount a=access(projectId,auth);return docs.findByProjectIdOrderByCreatedAtDesc(projectId).stream().filter(d->a.getUserType()!=UserType.CUSTOMER||d.isCustomerVisible()).map(this::view).toList();}
 @Transactional public DocumentView upload(Long projectId,Long documentId,String title,String note,boolean customerVisible,MultipartFile file,Authentication auth){if(file.isEmpty())throw new ApiException(HttpStatus.BAD_REQUEST,"请选择文件");Project p=managed(projectId,auth);UserAccount a=current(auth);Document d=documentId==null?docs.save(new Document(p,title.trim(),customerVisible,a)):docs.findById(documentId).filter(x->x.getProject().getId().equals(projectId)).orElseThrow(()->new ApiException(HttpStatus.BAD_REQUEST,"文档不属于项目"));d.update(title.trim(),customerVisible);int no=versions.maxVersion(d.getId())+1;String key=storage.save(file);versions.save(new DocumentVersion(d,no,key,Optional.ofNullable(file.getOriginalFilename()).orElse("file"),file.getContentType(),file.getSize(),note,a));audit.log(a,"DOCUMENT_VERSION_UPLOADED","DOCUMENT",d.getId(),Map.of("version",no,"file",Optional.ofNullable(file.getOriginalFilename()).orElse("file")));return view(d);}
 public Download download(Long versionId,Authentication auth){DocumentVersion v=versions.findWithDocumentById(versionId).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"文档版本不存在"));UserAccount a=access(v.getDocument().getProject().getId(),auth);if(a.getUserType()==UserType.CUSTOMER&&!v.getDocument().isCustomerVisible())throw new ApiException(HttpStatus.FORBIDDEN,"文档未授权客户");return new Download(storage.load(v.getStorageKey()),v.getFileName(),v.getContentType());}
 private DocumentView view(Document d){return new DocumentView(d.getId(),d.getTitle(),d.isCustomerVisible(),d.getCreatedBy().getDisplayName(),d.getCreatedAt(),versions.findByDocumentIdOrderByVersionNoDesc(d.getId()).stream().map(VersionView::from).toList());}
 private Project managed(Long id,Authentication auth){Project p=project(id);UserAccount a=current(auth);if(!a.getRoles().contains(Role.ADMIN)&&!p.getManager().getId().equals(a.getId()))throw new ApiException(HttpStatus.FORBIDDEN,"只有项目经理可以上传文档");return p;}
 private UserAccount access(Long id,Authentication auth){Project p=project(id);UserAccount a=current(auth);boolean ok=a.getRoles().contains(Role.ADMIN)||p.getManager().getId().equals(a.getId())||members.existsByProjectIdAndUserId(id,a.getId())||(p.getCustomer()!=null&&p.getCustomer().getId().equals(a.getId()));if(!ok)throw new ApiException(HttpStatus.FORBIDDEN,"无权查看文档");return a;}
 private Project project(Long id){return projects.findById(id).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"项目不存在"));} private UserAccount current(Authentication a){return users.findByUsernameIgnoreCase(a.getName()).orElseThrow();}
 public record DocumentView(Long id,String title,boolean customerVisible,String createdBy,Instant createdAt,List<VersionView> versions){}
 public record VersionView(Long id,int versionNo,String fileName,String contentType,long fileSize,String note,String uploadedBy,Instant uploadedAt){static VersionView from(DocumentVersion v){return new VersionView(v.getId(),v.getVersionNo(),v.getFileName(),v.getContentType(),v.getFileSize(),v.getNote(),v.getUploadedBy().getDisplayName(),v.getUploadedAt());}}
 public record Download(Resource resource,String fileName,String contentType){}
}
