package com.rcai.pm.report;

import com.rcai.pm.project.*; import com.rcai.pm.risk.*; import com.rcai.pm.user.*;
import org.springframework.security.core.Authentication; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import java.math.*; import java.time.*; import java.util.*; import java.util.stream.Collectors;

@Service @Transactional(readOnly=true)
public class ReportService{
 private final ProjectRepository projects; private final TaskItemRepository tasks; private final MilestoneRepository milestones; private final WorklogRepository worklogs; private final RiskRepository risks; private final DeliveryVersionRepository deliveries; private final UserAccountRepository users;
 public ReportService(ProjectRepository p,TaskItemRepository t,MilestoneRepository m,WorklogRepository w,RiskRepository r,DeliveryVersionRepository d,UserAccountRepository u){projects=p;tasks=t;milestones=m;worklogs=w;risks=r;deliveries=d;users=u;}
 public Summary report(LocalDate from,LocalDate to,ProjectType type,Long projectId,Long departmentId,Long ownerId,Long customerId,Authentication auth){UserAccount actor=users.findByUsernameIgnoreCase(auth.getName()).orElseThrow();List<Project> ps=(actor.getRoles().contains(Role.ADMIN)?projects.findAll():projects.findAccessible(actor.getId())).stream().filter(p->type==null||p.getProjectType()==type).filter(p->projectId==null||p.getId().equals(projectId)).filter(p->customerId==null||(p.getCustomer()!=null&&p.getCustomer().getId().equals(customerId))).toList();Set<Long> pids=ps.stream().map(Project::getId).collect(Collectors.toSet());List<TaskItem> ts=tasks.findAll().stream().filter(t->pids.contains(t.getProject().getId())).filter(t->ownerId==null||t.getOwner().getId().equals(ownerId)).filter(t->departmentId==null||Objects.equals(t.getOwner().getDepartmentId(),departmentId)).filter(t->inRange(t,from,to)).toList();long completed=ts.stream().filter(t->t.getStatus()==TaskStatus.COMPLETED).count();long overdue=ts.stream().filter(t->!List.of(TaskStatus.COMPLETED,TaskStatus.CANCELLED,TaskStatus.MERGED).contains(t.getStatus())&&t.getPlannedEndAt()!=null&&t.getPlannedEndAt().isBefore(LocalDateTime.now())).count();List<Milestone> ms=milestones.findAll().stream().filter(m->pids.contains(m.getProject().getId())).toList();long achieved=ms.stream().filter(m->m.getStatus()==ProjectStatus.COMPLETED).count();List<Worklog> ws=worklogs.findAll().stream().filter(w->pids.contains(w.getTask().getProject().getId())&&!w.getWorkedOn().isBefore(from)&&!w.getWorkedOn().isAfter(to)).toList();Map<String,BigDecimal> memberHours=ws.stream().collect(Collectors.groupingBy(w->w.getUser().getDisplayName(),Collectors.reducing(BigDecimal.ZERO,Worklog::getHours,BigDecimal::add)));Map<String,BigDecimal> deptLoad=ts.stream().collect(Collectors.groupingBy(t->t.getOwner().getDepartment()==null?"未分配":t.getOwner().getDepartment().getName(),Collectors.reducing(BigDecimal.ZERO,TaskItem::getEstimatedHours,BigDecimal::add)));Map<RiskLevel,Long> riskDistribution=risks.findAll().stream().filter(r->pids.contains(r.getProject().getId())).collect(Collectors.groupingBy(Risk::getRiskLevel,Collectors.counting()));List<DeliveryVersion> reviewed=deliveries.findAll().stream().filter(d->pids.contains(d.getTask().getProject().getId())&&d.getReviewedAt()!=null).toList();double avgHours=reviewed.stream().mapToLong(d->Duration.between(d.getSubmittedAt(),d.getReviewedAt()).toMinutes()).average().orElse(0)/60d;return new Summary(ps.size(),ts.size(),rate(completed,ts.size()),rate(overdue,ts.size()),rate(achieved,ms.size()),deptLoad,memberHours,riskDistribution,reviewed.size(),BigDecimal.valueOf(avgHours).setScale(1,RoundingMode.HALF_UP));}
 private boolean inRange(TaskItem t,LocalDate f,LocalDate to){if(t.getPlannedEndAt()==null&&t.getPlannedStartAt()==null)return true;LocalDate s=t.getPlannedStartAt()==null?t.getPlannedEndAt().toLocalDate():t.getPlannedStartAt().toLocalDate();LocalDate e=t.getPlannedEndAt()==null?s:t.getPlannedEndAt().toLocalDate();return !e.isBefore(f)&&!s.isAfter(to);}
 private BigDecimal rate(long n,long d){return d==0?BigDecimal.ZERO:BigDecimal.valueOf(n*100d/d).setScale(1,RoundingMode.HALF_UP);}
 public record Summary(int projectCount,int taskCount,BigDecimal completionRate,BigDecimal overdueRate,BigDecimal milestoneAchievementRate,Map<String,BigDecimal> departmentLoad,Map<String,BigDecimal> memberHours,Map<RiskLevel,Long> riskDistribution,int reviewedDeliveries,BigDecimal averageAcceptanceHours){}
}
